apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name:  shared
            mountPath: /data
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs"
  
