apiVersion: v1
kind: Namespace
metadata:
  name: python-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deploy
  namespace: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      namespace: python-api
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: cr.yandex/crp75cfq038hua7qn70s/python-api:latest
          imagePullPolicy: Never
