---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse 

  - src: git@github.com:vvyushmanov/vector-role.git
    scm: git
    version: "1.0.1"
    name: vector-role 

  - src: git@github.com:vvyushmanov/lighthouse-role.git
    scm: git
    version: "1.0.1"
    name: lighthouse-role 



    