apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: alertmanager-main
  namespace: monitoring
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: alertmanager-main
            port:
              name: web
        path: /alertmanager
        pathType: Prefix
