apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    name: multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
