version: "3.9"
services:
  postgres:
    container_name: postgresql
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
