apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-number-1
  labels: 
    app: nginx1
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 1180
        - containerPort: 11443
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
spec:
  selector:
    app: nginx1
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: multitool-http
    port: 1180
    targetPort: 1180
  - name:  multitool-https
    port: 11443
    targetPort: 11443
