kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-config-logs
  namespace: rbac
subjects:
- kind: User
  name: user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-config-logs-reader 
  apiGroup: rbac.authorization.k8s.io