apiVersion: v1
kind: Pod
metadata:
  namespace: rbac
  name: test-app
  labels:
    name: test-app
spec:
  containers:
  - name: test-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
