apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.appVersion | default .Chart.AppVersion }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
          - name:  index
            mountPath:  /usr/share/nginx/html
      volumes:
        - name:  index
          configMap:
            name: {{ .Chart.Name }}-{{ .Release.Name }}-webpage-cm
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}