apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-{{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /{{ .Release.Namespace}}/{{ .Release.Name }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-{{ .Release.Name }}
            port:
              number: {{ .Values.port }}