all:
  hosts:
    node1:
      ansible_host: 158.160.56.189
      ip: 192.168.10.21
    node2:
      ansible_host: 158.160.65.137
      ip: 192.168.11.17
    node3:
      ansible_host: 51.250.28.37
      ip: 192.168.11.30
    node4:
      ansible_host: 51.250.44.9
      ip: 192.168.12.14
  vars:
    loadbalancer_apiserver: 
      address: 158.160.68.24
      port: 6443
    apiserver_loadbalancer_domain_name: 158.160.68.24
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
