all:
  hosts:
    node1:
      ansible_host: 84.201.172.52
      ip: 192.168.10.6
    node2:
      ansible_host: 158.160.18.243
      ip: 192.168.11.14
    node3:
      ansible_host: 51.250.108.251
      ip: 192.168.11.20
    node4:
      ansible_host: 51.250.44.158
      ip: 192.168.12.17
  vars:
    loadbalancer_apiserver: 
      address: 158.160.81.80
      port: 6443
    apiserver_loadbalancer_domain_name: 158.160.81.80
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
