all:
  hosts:
    node1:
      ansible_host: 158.160.117.37
      ip: 192.168.10.11
    node2:
      ansible_host: 158.160.65.141
      ip: 192.168.11.32
    node3:
      ansible_host: 158.160.84.169
      ip: 192.168.11.21
    node4:
      ansible_host: 51.250.37.86
      ip: 192.168.12.12
  vars:
    loadbalancer_apiserver: 
      address: 158.160.82.136
      port: 6443
    apiserver_loadbalancer_domain_name: 158.160.82.136
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
        node4:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
