all:
  hosts:
    node1:
      ansible_host: 158.160.126.19
      ip: 192.168.10.29
    node2:
      ansible_host: 158.160.17.120
      ip: 192.168.11.22
    node3:
      ansible_host: 51.250.40.123
      ip: 192.168.12.18
  vars:
    loadbalancer_apiserver: 
      address: 158.160.10.159
      port: 6443
    apiserver_loadbalancer_domain_name: 158.160.10.159
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
