all:
  hosts:
    node1:
      ansible_host: 62.84.112.228
      ip: 192.168.10.6
    node2:
      ansible_host: 51.250.30.74
      ip: 192.168.11.29
    node3:
      ansible_host: 158.160.29.168
      ip: 192.168.11.13
    node4:
      ansible_host: 51.250.46.191
      ip: 192.168.12.8
  vars:
    loadbalancer_apiserver: 
      address: 130.193.42.70
      port: 6443
    apiserver_loadbalancer_domain_name: 130.193.42.70
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
