all:
  hosts:
    node1:
      ansible_host: 158.160.109.240
      ip: 192.168.10.35
    node2:
      ansible_host: 158.160.84.185
      ip: 192.168.11.9
    node3:
      ansible_host: 51.250.41.214
      ip: 192.168.12.26
  vars:
    loadbalancer_apiserver: 
      address: 158.160.77.219
      port: 6443
    apiserver_loadbalancer_domain_name: 158.160.77.219
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
