apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k8s
spec:
  selector:
    matchLabels:
      app: nginx-k8s
  template:
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
      - name: nginx-k8s
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  index
            mountPath:  /usr/share/nginx/html
      volumes:
        - name:  index
          configMap:
            name: webpage-cm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s
spec:
  selector:
    app: nginx-k8s
  ports:
  - port: 80
    targetPort: 80
