apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-bb
spec:
  selector:
    matchLabels:
      app: mt-bb
  template:
    metadata:
      labels:
        app: mt-bb
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sh
          - -c 
          - 'while true; do sleep 3600; done'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name:  HTTP_PORT
            valueFrom:
              configMapKeyRef:
                key: http_alt
                name:  env
