apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 500Mi
  hostPath:
    path:
      /tmp/pvdemo
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle


    
