all:
  hosts:
    node1:
      ansible_host: 158.160.40.60
      ip: 192.168.10.6
    node2:
      ansible_host: 158.160.68.105
      ip: 192.168.11.5
    node3:
      ansible_host: 158.160.84.191
      ip: 192.168.11.12
    node4:
      ansible_host: 51.250.47.14
      ip: 192.168.12.4
  vars:
    loadbalancer_apiserver: 
      address: 51.250.41.238
      port: 6443
    apiserver_loadbalancer_domain_name: 51.250.41.238
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
