all:
  hosts:
    node1:
      ansible_host: 158.160.57.91
      ip: 192.168.10.32
      access_ip: 192.168.10.32
    node2:
      ansible_host: 158.160.57.233
      ip: 192.168.10.30
      access_ip: 192.168.10.30
    node3:
      ansible_host: 158.160.60.240
      ip: 192.168.10.26
      access_ip: 192.168.10.26
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
