all:
  hosts:
    node1:
      ansible_host: 158.160.52.158
      ip: 192.168.10.18
      loadbalancer_apiserver: 
        address: 51.250.69.108
      apiserver_loadbalancer_domain_name: 51.250.69.108
    node2:
      ansible_host: 158.160.2.105
      ip: 192.168.11.4
      loadbalancer_apiserver: 
        address: 51.250.69.108
      apiserver_loadbalancer_domain_name: 51.250.69.108
    node3:
      ansible_host: 51.250.45.132
      ip: 192.168.12.5
      loadbalancer_apiserver: 
        address: 51.250.69.108
      apiserver_loadbalancer_domain_name: 51.250.69.108
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
