version: "3.9"
services:
  postgres_2:
    container_name: test_db_restored
    image: postgres:12
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./backup:/var/backups
    restart: always
