filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    # json.message_key: log
    # json.keys_under_root: true
    # json.add_error_key: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5046"]
  protocol: tcp

  # codec.json:
  #   pretty: true

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
